export const WineActionTypes = {
    FETCH_WINE_REQUEST: "FETCH_WINE_REQUEST",
    FETCH_WINE_SUCCESS: "FETCH_WINE_SUCCESS",
    FETCH_WINE_FAILURE: "FETCH_WINE_FAILURE"
}

export const CurrentWineActionTypes = {
    FETCH_CURRENT_WINE_REQUEST: "FETCH_CURRENT_WINE_REQUEST",
    FETCH_CURRENT_WINE_SUCCESS: "FETCH_CURRENT_WINE_SUCCESS",
    FETCH_CURRENT_WINE_FAILURE: "FETCH_CURRENT_WINE_FAILURE"
}

